### PR TITLE
#216 first draft. generateHTML and htmlSanityCheck works

### PR DESCRIPTION
**Pull request by rdmueller**
see #216 for more details

### CODE REVIEW

**Comment by rdmueller** [comment]
ok. still fighting with travis, just give me some additional time :-)

**Comment by gernotstarke** [comment]
hhm - Travis build fails: @rdmueller, could you please have a look?

**Comment by rdmueller** [comment]
yeah, already working on this...

**Comment by rdmueller** [comment]
wow. three different build environments (travis, ps and bash) and three different errors for the target "check"

**Comment by rdmueller** [comment]
wow. that was a hard one:
- on a windows system there are 4 failing tests in RC2
- somehow I had to reference mavencentral and jcenter as repositories for the codenarc plugin to work
- the check task also invoked the docToolchain checks which currently fail on a linux system *g*

**please sqash this PR when you accept it!**

**Comment by gernotstarke** [comment]
thanx Ralf - a nice step forward in documentation!

**Pull request merged**
