### PR TITLE
Change HtmlSanityCheckTask.sourceDocuments to a FileCollection.

### PR DESCRIPTION
**Pull request by erdi**
This PR contains a fix for #264. 

I had to deviate a bit from the original proposal in #264 as it turns out that the value for `Configuration.ITEM_NAME_sourceDir` is used in a number of checkers so I did not remove it in the end.

### CODE REVIEW

**Comment by gernotstarke** [comment]
thank you very much for solving #264 so quickly...

**Comment by erdi** [comment]
Thanks for merging this swiftly, @gernotstarke. 

Do you have any plans to cut a new release anytime soon? With the changes we required now in master we could ditch our fork as soon as they get released.

**Comment by gernotstarke** [comment]
just released/published 1.1.0

Could you give me any indication if the new release works for you?
Thanx!

**Comment by erdi** [comment]
I have just tried out 1.1.0 but it does not seem to contain any of the changes I have contributed - `sourceDocuments` is still a `Set` and `checkerClasses` is not a known property on `HtmlSanityCheckTask`. Which revision have you published the artifacts from? I looked for a tag for 1.1.0 at https://github.com/aim42/htmlSanityCheck/releases but couldn't find it...

**Comment by gernotstarke** [comment]
mea culpa - I did it wrong. Will look into it immediately... (too bad I've got a day-job with certain priorities aside from open-source)

**Comment by erdi** [comment]
No worries Gernot, we're all in the same boat! Take your time, it's not
blocking for us or anything so there's no rush.

**Comment by gernotstarke** [comment]
published again, this time after (really) merging your changes and properly testing.

Re-used the same version label (1.1.0).

**Comment by erdi** [comment]
I can confirm that it now works as expected, thank you very much!

**Pull request merged**
